<?php
/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The Diacritize service implementation
 *
 * Generated by http://code.google.com/p/google-api-php-client/
 * Generated from: https://www.googleapis.com/discovery/v0.3/describe/diacritize/v1
 **/
class apiDiacritizeService {

  // Variables that the apiServiceResource implementation depends on
  private $serviceName = 'diacritize';
  private $version = 'v1';
  private $restBasePath = 'https://www.googleapis.com/language/diacritize/';
  private $rpcPath = 'https://www.googleapis.com/rpc';
  private $io;
  // apiServiceResource's that are used internally
  private $diacritize;

  /**
   * Constructs the internal service representations and does the auto-magic configuration required to drive them
   */
  public function __construct(apiClient $apiClient) {
    $apiClient->addService('diacritize', 'v1');
    $this->io = $apiClient->getIo();
    $this->diacritize = new apiServiceResource($this, $this->serviceName, 'diacritize', json_decode('{"resources":{"corpus":{"methods":{"get":{"restPath":"v1","rpcMethod":"language.diacritize.corpus.get","httpMethod":"GET","description":"Adds diacritical marks to the given message.","parameters":{"lang":{"restParameterType":"query","required":true,"description":"Language of the message","type":"string"},"last_letter":{"restParameterType":"query","required":true,"description":"Flag to indicate whether the last letter in a word should be diacritized or not","type":"boolean"},"message":{"restParameterType":"query","required":true,"description":"Message to be diacritized","type":"string"}},"parameterOrder":["lang","last_letter","message"],"response":{"$ref":"LanguageDiacritizeCorpusResource"}}}}}}', true));
  }

  /**
   * @return the $io
   */
  public function getIo() {
    return $this->io;
  }

  /**
   * @return the $version
   */
  public function getVersion() {
    return $this->version;
  }

  /**
   * @return the $restBasePath
   */
  public function getRestBasePath() {
    return $this->restBasePath;
  }

  /**
   * @return the $rpcPath
   */
  public function getRpcPath() {
    return $this->rpcPath;
  }
}

